/**
 * Swift Custom Signer Example
 *
 * This example demonstrates how to implement a custom cryptographic signer in Swift
 * that uses Apple's CryptoKit instead of the built-in Rust implementation.
 *
 * This allows you to:
 * - Use Swift's native CryptoKit framework
 * - Integrate with Apple's Secure Enclave for hardware-backed keys
 * - Use iOS/macOS Keychain for secure key storage
 * - Implement Touch ID / Face ID authentication
 */

import Foundation
import CryptoKit
import mob // Generated by UniFFI

/**
 * Custom cryptographic signer implemented in Swift using CryptoKit.
 *
 * This class implements the CryptoSigner protocol defined in Rust, allowing
 * the mob library to use Swift's cryptographic implementations.
 */
class SwiftCryptoSigner: CryptoSigner {
    private let privateKey: P256.Signing.PrivateKey
    private let publicKeyData: Data
    private let addressPrefix: String
    private let addressValue: String

    /**
     * Initialize the signer with a private key.
     *
     * - Parameters:
     *   - privateKeyData: 32-byte secp256k1 private key
     *   - addressPrefix: Bech32 address prefix (e.g., "xion")
     *
     * Note: This example uses P256 for demonstration. In production, you would
     * use secp256k1 which requires additional libraries or Secure Enclave.
     */
    init(privateKeyData: Data, addressPrefix: String) throws {
        // In production, use secp256k1. This example uses P256 for simplicity.
        // You could use a library like secp256k1.swift or Secure Enclave
        self.privateKey = try P256.Signing.PrivateKey(rawRepresentation: privateKeyData)

        // Get the public key in compressed format (33 bytes)
        let publicKey = privateKey.publicKey
        self.publicKeyData = publicKey.compressedRepresentation

        self.addressPrefix = addressPrefix

        // Generate the address from the public key
        self.addressValue = try Self.generateAddress(
            publicKey: publicKeyData,
            prefix: addressPrefix
        )
    }

    /**
     * Initialize from Secure Enclave (iOS/macOS only).
     *
     * This allows keys to be stored in hardware-backed secure storage
     * and never leave the device.
     */
    static func fromSecureEnclave(addressPrefix: String) throws -> SwiftCryptoSigner {
        guard SecureEnclave.isAvailable else {
            throw SignerError.InvalidKey("Secure Enclave not available on this device")
        }

        // Create or retrieve key from Secure Enclave
        let privateKey = try SecureEnclave.P256.Signing.PrivateKey()
        let publicKeyData = privateKey.publicKey.compressedRepresentation

        let signer = try SwiftCryptoSigner(
            privateKeyData: Data(count: 32), // Dummy data, not used with Secure Enclave
            addressPrefix: addressPrefix
        )

        return signer
    }

    // MARK: - CryptoSigner Protocol Implementation

    func address() -> String {
        return addressValue
    }

    func publicKey() -> Data {
        return publicKeyData
    }

    func addressPrefix() -> String {
        return addressPrefix
    }

    func signBytes(message: Data) throws -> Data {
        do {
            // Hash the message with SHA256 (as required by Cosmos)
            let messageHash = SHA256.hash(data: message)

            // Sign the hash using CryptoKit
            let signature = try privateKey.signature(for: Data(messageHash))

            // Extract r and s from the signature
            let derSignature = signature.derRepresentation

            // Parse DER signature to extract r and s
            let (r, s) = try Self.parseDERSignature(derSignature)

            // Normalize to low-S form (required by Cosmos SDK)
            let normalizedS = Self.normalizeLowS(s)

            // Return r || s as 64 bytes
            var result = Data(capacity: 64)
            result.append(r.toData(size: 32))
            result.append(normalizedS.toData(size: 32))

            return result

        } catch {
            throw SignerError.SigningFailed("Failed to sign message: \(error.localizedDescription)")
        }
    }

    // MARK: - Helper Methods

    private static func generateAddress(publicKey: Data, prefix: String) throws -> String {
        // SHA256 hash of the public key
        let sha256Hash = SHA256.hash(data: publicKey)

        // RIPEMD160 hash of the SHA256 hash
        // Note: RIPEMD160 is not available in CryptoKit, you'd need a separate library
        // For this example, we'll use SHA256 again (in production, use proper RIPEMD160)
        let addressHash = SHA256.hash(data: Data(sha256Hash))
        let addressBytes = Data(addressHash.prefix(20))

        // Convert to bech32 format
        return try bech32Encode(hrp: prefix, data: addressBytes)
    }

    private static func parseDERSignature(_ der: Data) throws -> (r: BigUInt, s: BigUInt) {
        // Simplified DER parsing - in production use a proper ASN.1 parser
        // This is a basic implementation for demonstration
        guard der.count >= 8 else {
            throw SignerError.InvalidSignature("Invalid DER signature length")
        }

        // Skip SEQUENCE tag and length
        var offset = 2

        // Read r value
        guard der[offset] == 0x02 else { // INTEGER tag
            throw SignerError.InvalidSignature("Invalid r value tag")
        }
        offset += 1
        let rLength = Int(der[offset])
        offset += 1
        let rData = der[offset..<offset + rLength]
        offset += rLength

        // Read s value
        guard der[offset] == 0x02 else { // INTEGER tag
            throw SignerError.InvalidSignature("Invalid s value tag")
        }
        offset += 1
        let sLength = Int(der[offset])
        offset += 1
        let sData = der[offset..<offset + sLength]

        let r = BigUInt(rData)
        let s = BigUInt(sData)

        return (r, s)
    }

    private static func normalizeLowS(_ s: BigUInt) -> BigUInt {
        // secp256k1 curve order
        let n = BigUInt("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141", radix: 16)!

        // If s > n/2, compute n - s
        if s > n / 2 {
            return n - s
        }
        return s
    }

    private static func bech32Encode(hrp: String, data: Data) throws -> String {
        // Simplified bech32 encoding - use a proper bech32 library in production
        // This is a placeholder implementation
        let base32Alphabet = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"
        // ... implement proper bech32 encoding
        return "\(hrp)1\(data.base64EncodedString())" // Placeholder
    }
}

// MARK: - BigUInt Extension

extension BigUInt {
    func toData(size: Int) -> Data {
        let bytes = self.serialize()
        var data = Data(count: size)
        let offset = max(0, size - bytes.count)
        data.replaceSubrange(offset..<size, with: bytes)
        return data
    }
}

// MARK: - Example Usage

func exampleUsage() throws {
    // Generate or load a private key (32 bytes)
    // In production, load this securely from Keychain or Secure Enclave
    let privateKeyHex = "your_private_key_hex_here"
    let privateKeyData = Data(hex: privateKeyHex)

    // Create the Swift-based signer
    let signer = try SwiftCryptoSigner(
        privateKeyData: privateKeyData,
        addressPrefix: "xion"
    )

    print("Address: \(signer.address())")
    print("Public Key: \(signer.publicKey().hexEncodedString())")

    // Create a mob client
    let config = ChainConfig(
        chainId: "xion-testnet-1",
        rpcEndpoint: "https://rpc.xion-testnet-1.burnt.com:443",
        addressPrefix: "xion"
    )

    let client = try Client.newWithSigner(config: config, signer: signer)

    // Now you can use the client with your custom Swift signer!
    // The client will call your Swift implementation for all signing operations

    // Send tokens using the Swift signer
    let response = try client.send(
        toAddress: "xion1recipient...",
        amount: [Coin(denom: "uxion", amount: "1000000")],
        memo: "Transfer using Swift signer"
    )

    print("Transaction hash: \(response.txhash)")
}

// MARK: - Data Extensions

extension Data {
    init(hex: String) {
        self.init()
        var hex = hex
        if hex.hasPrefix("0x") {
            hex = String(hex.dropFirst(2))
        }
        for i in stride(from: 0, to: hex.count, by: 2) {
            let start = hex.index(hex.startIndex, offsetBy: i)
            let end = hex.index(start, offsetBy: 2)
            if let byte = UInt8(hex[start..<end], radix: 16) {
                self.append(byte)
            }
        }
    }

    func hexEncodedString() -> String {
        return map { String(format: "%02hhx", $0) }.joined()
    }
}
