# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .rb file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Ruby
# helpers directly inline like we're doing here.

require 'ffi'


module Mob
  def self.uniffi_in_range(i, type_name, min, max)
  raise TypeError, "no implicit conversion of #{i} into Integer" unless i.respond_to?(:to_int)
  i = i.to_int
  raise RangeError, "#{type_name} requires #{min} <= value < #{max}" unless (min <= i && i < max)
  i
end

def self.uniffi_utf8(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v = v.to_str.encode(Encoding::UTF_8)
  raise Encoding::InvalidByteSequenceError, "not a valid UTF-8 encoded string" unless v.valid_encoding?
  v
end

def self.uniffi_bytes(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v.to_str
end

  class RustBuffer < FFI::Struct
  layout :capacity, :uint64,
         :len,      :uint64,
         :data,     :pointer

  def self.alloc(size)
    return Mob.rust_call(:ffi_mob_rustbuffer_alloc, size)
  end

  def self.reserve(rbuf, additional)
    return Mob.rust_call(:ffi_mob_rustbuffer_reserve, rbuf, additional)
  end

  def free
    Mob.rust_call(:ffi_mob_rustbuffer_free, self)
  end

  def capacity
    self[:capacity]
  end

  def len
    self[:len]
  end

  def len=(value)
    self[:len] = value
  end

  def data
    self[:data]
  end

  def to_s
    "RustBuffer(capacity=#{capacity}, len=#{len}, data=#{data.read_bytes len})"
  end

  # The allocated buffer will be automatically freed if an error occurs, ensuring that
  # we don't accidentally leak it.
  def self.allocWithBuilder
    builder = RustBufferBuilder.new

    begin
      yield builder
    rescue => e
      builder.discard
      raise e
    end
  end

  # The RustBuffer will be freed once the context-manager exits, ensuring that we don't
  # leak it even if an error occurs.
  def consumeWithStream
    stream = RustBufferStream.new self

    yield stream

    raise RuntimeError, 'junk data left in buffer after consuming' if stream.remaining != 0
  ensure
    free
  end# The primitive String type.

  def self.allocFromString(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write value.encode('utf-8')
      return builder.finalize
    end
  end

  def consumeIntoString
    consumeWithStream do |stream|
      return stream.read(stream.remaining).force_encoding(Encoding::UTF_8)
    end
  end

  # The primitive Bytes type.

  def self.allocFromBytes(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Bytes(value)
      return builder.finalize
    end
  end

  def consumeIntoBytes
    consumeWithStream do |stream|
      return stream.readBytes
    end
  end

  # The Record type AccountInfo.

  def self.check_lower_TypeAccountInfo(v)
    
    
    
    RustBuffer.check_lower_Optionalstring(v.pub_key)
  end

  def self.alloc_from_TypeAccountInfo(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeAccountInfo(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeAccountInfo
    consumeWithStream do |stream|
      return stream.readTypeAccountInfo
    end
  end

  # The Record type ChainConfig.

  def self.check_lower_TypeChainConfig(v)
    
    
    RustBuffer.check_lower_Optionalstring(v.grpc_endpoint)
    
    
    
  end

  def self.alloc_from_TypeChainConfig(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeChainConfig(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeChainConfig
    consumeWithStream do |stream|
      return stream.readTypeChainConfig
    end
  end

  # The Record type Coin.

  def self.check_lower_TypeCoin(v)
    
    
  end

  def self.alloc_from_TypeCoin(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeCoin(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeCoin
    consumeWithStream do |stream|
      return stream.readTypeCoin
    end
  end

  # The Record type Fee.

  def self.check_lower_TypeFee(v)
    RustBuffer.check_lower_SequenceTypeCoin(v.amount)
    
    RustBuffer.check_lower_Optionalstring(v.payer)
    RustBuffer.check_lower_Optionalstring(v.granter)
  end

  def self.alloc_from_TypeFee(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeFee(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeFee
    consumeWithStream do |stream|
      return stream.readTypeFee
    end
  end

  # The Record type TxResponse.

  def self.check_lower_TypeTxResponse(v)
    
    
    
    
    
    
  end

  def self.alloc_from_TypeTxResponse(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeTxResponse(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeTxResponse
    consumeWithStream do |stream|
      return stream.readTypeTxResponse
    end
  end

  # The Enum type BroadcastMode.

  def self.check_lower_TypeBroadcastMode(v)
  end

  def self.alloc_from_TypeBroadcastMode(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_TypeBroadcastMode(v)
      return builder.finalize
    end
  end

  def consumeIntoTypeBroadcastMode
    consumeWithStream do |stream|
      return stream.readTypeBroadcastMode
    end
  end
  

  

  # The Optional<T> type for string.

  def self.check_lower_Optionalstring(v)
    if not v.nil?
      
    end
  end

  def self.alloc_from_Optionalstring(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Optionalstring(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalstring
    consumeWithStream do |stream|
      return stream.readOptionalstring
    end
  end

  # The Sequence<T> type for TypeCoin.

  def self.check_lower_SequenceTypeCoin(v)
    v.each do |item|
      RustBuffer.check_lower_TypeCoin(item)
    end
  end

  def self.alloc_from_SequenceTypeCoin(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_SequenceTypeCoin(v)
      return builder.finalize()
    end
  end

  def consumeIntoSequenceTypeCoin
    consumeWithStream do |stream|
      return stream.readSequenceTypeCoin
    end
  end

  
end

module UniFFILib
  class ForeignBytes < FFI::Struct
    layout :len,      :int32,
           :data,     :pointer

    def len
      self[:len]
    end

    def data
      self[:data]
    end

    def to_s
      "ForeignBytes(len=#{len}, data=#{data.read_bytes(len)})"
    end
  end
end

private_constant :UniFFILib
  
# Helper for structured reading of values from a RustBuffer.
class RustBufferStream

  def initialize(rbuf)
    @rbuf = rbuf
    @offset = 0
  end

  def remaining
    @rbuf.len - @offset
  end

  def read(size)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    data = @rbuf.data.get_bytes @offset, size

    @offset += size

    data
  end

  def readU32
    unpack_from 4, 'L>'
  end

  def readU64
    unpack_from 8, 'Q>'
  end

  def readI64
    unpack_from 8, 'q>'
  end

  def readBool
    v = unpack_from 1, 'c'

    return false if v == 0
    return true if v == 1

    raise InternalError, 'Unexpected byte for Boolean type'
  end

  def readString
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative string length' if size.negative?

    read(size).force_encoding(Encoding::UTF_8)
  end

  def readBytes
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative byte string length' if size.negative?

    read(size).force_encoding(Encoding::BINARY)
  end

  # The Object type Client.

  def readTypeClient
    handle = unpack_from 8, 'Q>'
    return Client.uniffi_allocate(handle)
  end

  # The Object type Signer.

  def readTypeSigner
    handle = unpack_from 8, 'Q>'
    return Signer.uniffi_allocate(handle)
  end

  # The Record type AccountInfo.

  def readTypeAccountInfo
    AccountInfo.new(
      address: readString,
      account_number: readU64,
      sequence: readU64,
      pub_key: readOptionalstring
    )
  end

  # The Record type ChainConfig.

  def readTypeChainConfig
    ChainConfig.new(
      chain_id: readString,
      rpc_endpoint: readString,
      grpc_endpoint: readOptionalstring,
      address_prefix: readString,
      coin_type: readU32,
      gas_price: readString
    )
  end

  # The Record type Coin.

  def readTypeCoin
    Coin.new(
      denom: readString,
      amount: readString
    )
  end

  # The Record type Fee.

  def readTypeFee
    Fee.new(
      amount: readSequenceTypeCoin,
      gas_limit: readU64,
      payer: readOptionalstring,
      granter: readOptionalstring
    )
  end

  # The Record type TxResponse.

  def readTypeTxResponse
    TxResponse.new(
      txhash: readString,
      code: readU32,
      raw_log: readString,
      gas_wanted: readU64,
      gas_used: readU64,
      height: readI64
    )
  end

  
  
  # The Enum type BroadcastMode.

  def readTypeBroadcastMode
    variant = unpack_from 4, 'l>'
    
    if variant == 1
      return BroadcastMode::SYNC
    end
    if variant == 2
      return BroadcastMode::ASYNC
    end
    if variant == 3
      return BroadcastMode::BLOCK
    end

    raise InternalError, 'Unexpected variant tag for TypeBroadcastMode'
  end

  

  

  

  # The Error type MobError

  def readTypeMobError
    variant = unpack_from 4, 'l>'
    
    if variant == 1
      return MobError::Rpc.new(
        readString()
      )
    end
    if variant == 2
      return MobError::Transaction.new(
        readString()
      )
    end
    if variant == 3
      return MobError::Signing.new(
        readString()
      )
    end
    if variant == 4
      return MobError::KeyDerivation.new(
        readString()
      )
    end
    if variant == 5
      return MobError::Address.new(
        readString()
      )
    end
    if variant == 6
      return MobError::Serialization.new(
        readString()
      )
    end
    if variant == 7
      return MobError::InvalidInput.new(
        readString()
      )
    end
    if variant == 8
      return MobError::Account.new(
        readString()
      )
    end
    if variant == 9
      return MobError::Network.new(
        readString()
      )
    end
    if variant == 10
      return MobError::GasEstimation.new(
        readString()
      )
    end
    if variant == 11
      return MobError::InsufficientFunds.new(
        readString()
      )
    end
    if variant == 12
      return MobError::Timeout.new(
        readString()
      )
    end
    if variant == 13
      return MobError::Generic.new(
        readString()
      )
    end

    raise InternalError, 'Unexpected variant tag for TypeMobError'
  end
  

  # The Optional<T> type for string.

  def readOptionalstring
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readString
    else
      raise InternalError, 'Unexpected flag byte for Optionalstring'
    end
  end

  # The Sequence<T> type for TypeCoin.

  def readSequenceTypeCoin
    count = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative sequence length' if count.negative?

    items = []

    count.times do
      items.append readTypeCoin
    end

    items
  end

  

  def unpack_from(size, format)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    value = @rbuf.data.get_bytes(@offset, size).unpack format

    @offset += size

    # TODO: verify this
    raise 'more than one element!!!' if value.size > 1

    value[0]
  end
end

private_constant :RustBufferStream
  
# Helper for structured writing of values into a RustBuffer.
class RustBufferBuilder
  def initialize
    @rust_buf = RustBuffer.alloc 16
    @rust_buf.len = 0
  end

  def finalize
    rbuf = @rust_buf

    @rust_buf = nil

    rbuf
  end

  def discard
    return if @rust_buf.nil?

    rbuf = finalize
    rbuf.free
  end

  def write(value)
    reserve(value.bytes.size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, value.bytes
    end
  end

  def write_U32(v)
    v = Mob::uniffi_in_range(v, "u32", 0, 2**32)
    pack_into(4, 'L>', v)
  end

  def write_U64(v)
    v = Mob::uniffi_in_range(v, "u64", 0, 2**64)
    pack_into(8, 'Q>', v)
  end

  def write_I64(v)
    v = Mob::uniffi_in_range(v, "i64", -2**63, 2**63)
    pack_into(8, 'q>', v)
  end

  def write_Bool(v)
    pack_into(1, 'c', v ? 1 : 0)
  end

  def write_String(v)
    v = Mob::uniffi_utf8(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  def write_Bytes(v)
    v = Mob::uniffi_bytes(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  # The Object type Client.

  def write_TypeClient(obj)
    handle = Client.uniffi_lower obj
    pack_into(8, 'Q>', handle)
  end

  # The Object type Signer.

  def write_TypeSigner(obj)
    handle = Signer.uniffi_lower obj
    pack_into(8, 'Q>', handle)
  end

  # The Record type AccountInfo.

  def write_TypeAccountInfo(v)
    self.write_String(v.address)
    self.write_U64(v.account_number)
    self.write_U64(v.sequence)
    self.write_Optionalstring(v.pub_key)
  end

  # The Record type ChainConfig.

  def write_TypeChainConfig(v)
    self.write_String(v.chain_id)
    self.write_String(v.rpc_endpoint)
    self.write_Optionalstring(v.grpc_endpoint)
    self.write_String(v.address_prefix)
    self.write_U32(v.coin_type)
    self.write_String(v.gas_price)
  end

  # The Record type Coin.

  def write_TypeCoin(v)
    self.write_String(v.denom)
    self.write_String(v.amount)
  end

  # The Record type Fee.

  def write_TypeFee(v)
    self.write_SequenceTypeCoin(v.amount)
    self.write_U64(v.gas_limit)
    self.write_Optionalstring(v.payer)
    self.write_Optionalstring(v.granter)
  end

  # The Record type TxResponse.

  def write_TypeTxResponse(v)
    self.write_String(v.txhash)
    self.write_U32(v.code)
    self.write_String(v.raw_log)
    self.write_U64(v.gas_wanted)
    self.write_U64(v.gas_used)
    self.write_I64(v.height)
  end

  # The Enum type BroadcastMode.

  def write_TypeBroadcastMode(v)
    pack_into(4, 'l>', v)
 end
   

  

  # The Optional<T> type for string.

  def write_Optionalstring(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_String(v)
    end
  end

  # The Sequence<T> type for TypeCoin.

  def write_SequenceTypeCoin(items)
    pack_into(4, 'l>', items.size)

    items.each do |item|
      self.write_TypeCoin(item)
    end
  end

  

  private

  def reserve(num_bytes)
    if @rust_buf.len + num_bytes > @rust_buf.capacity
      @rust_buf = RustBuffer.reserve(@rust_buf, num_bytes)
    end

    yield

    @rust_buf.len += num_bytes
  end

  def pack_into(size, format, value)
    reserve(size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, [value].pack(format).bytes
    end
  end
end

private_constant :RustBufferBuilder

  # Error definitions
  class RustCallStatus < FFI::Struct
  layout :code,    :int8,
         :error_buf, RustBuffer

  def code
    self[:code]
  end

  def error_buf
    self[:error_buf]
  end

  def to_s
    "RustCallStatus(code=#{self[:code]})"
  end
end

# These match the values from the uniffi::rustcalls module
CALL_SUCCESS = 0
CALL_ERROR = 1
CALL_PANIC = 2



class MobError
    Rpc = Class.new StandardError
    Transaction = Class.new StandardError
    Signing = Class.new StandardError
    KeyDerivation = Class.new StandardError
    Address = Class.new StandardError
    Serialization = Class.new StandardError
    InvalidInput = Class.new StandardError
    Account = Class.new StandardError
    Network = Class.new StandardError
    GasEstimation = Class.new StandardError
    InsufficientFunds = Class.new StandardError
    Timeout = Class.new StandardError
    Generic = Class.new StandardError

end


# Map error modules to the RustBuffer method name that reads them
ERROR_MODULE_TO_READER_METHOD = {


  MobError => :readTypeMobError,

}

private_constant :ERROR_MODULE_TO_READER_METHOD, :CALL_SUCCESS, :CALL_ERROR, :CALL_PANIC,
                 :RustCallStatus

def self.consume_buffer_into_error(error_module, rust_buffer)
  rust_buffer.consumeWithStream do |stream|
    reader_method = ERROR_MODULE_TO_READER_METHOD[error_module]
    return stream.send(reader_method)
  end
end

class InternalError < StandardError
end

def self.rust_call(fn_name, *args)
  # Call a rust function
  rust_call_with_error(nil, fn_name, *args)
end

def self.rust_call_with_error(error_module, fn_name, *args)
  # Call a rust function and handle errors
  #
  # Use this when the rust function returns a Result<>.  error_module must be the error_module that corresponds to that Result.


  # Note: RustCallStatus.new zeroes out the struct, which is exactly what we
  # want to pass to Rust (code=0, error_buf=RustBuffer(len=0, capacity=0,
  # data=NULL))
  status = RustCallStatus.new
  args << status

  result = UniFFILib.public_send(fn_name, *args)

  case status.code
  when CALL_SUCCESS
    result
  when CALL_ERROR
    if error_module.nil?
      status.error_buf.free
      raise InternalError, "CALL_ERROR with no error_module set"
    else
      raise consume_buffer_into_error(error_module, status.error_buf)
    end
  when CALL_PANIC
    # When the rust code sees a panic, it tries to construct a RustBuffer
    # with the message.  But if that code panics, then it just sends back
    # an empty buffer.
    if status.error_buf.len > 0
      raise InternalError, status.error_buf.consumeIntoString()
    else
      raise InternalError, "Rust panic"
    end
  else
    raise InternalError, "Unknown call status: #{status.code}"
  end
end

private_class_method :consume_buffer_into_error

  # This is how we find and load the dynamic library provided by the component.
# For now we just look it up by name.
module UniFFILib
  extend FFI::Library

  
  ffi_lib File.expand_path('libmob.dylib', __dir__)
  

  attach_function :uniffi_mob_fn_clone_client,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_mob_fn_free_client,
    [:uint64, RustCallStatus.by_ref],
    :void
  attach_function :uniffi_mob_fn_constructor_client_new,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_mob_fn_constructor_client_new_with_signer,
    [RustBuffer.by_value, :uint64, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_mob_fn_method_client_attach_signer,
    [:uint64, :uint64, RustCallStatus.by_ref],
    :void
  attach_function :uniffi_mob_fn_method_client_execute_contract,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_client_get_account,
    [:uint64, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_client_get_all_balances,
    [:uint64, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_client_get_balance,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_client_get_chain_id,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_client_get_height,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_mob_fn_method_client_get_tx,
    [:uint64, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_client_is_synced,
    [:uint64, RustCallStatus.by_ref],
    :int8
  attach_function :uniffi_mob_fn_method_client_send,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_clone_signer,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_mob_fn_free_signer,
    [:uint64, RustCallStatus.by_ref],
    :void
  attach_function :uniffi_mob_fn_constructor_signer_from_mnemonic,
    [RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, RustCallStatus.by_ref],
    :uint64
  attach_function :uniffi_mob_fn_method_signer_address,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_signer_address_prefix,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_signer_public_key_hex,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_fn_method_signer_sign_bytes,
    [:uint64, RustBuffer.by_value, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_mob_rustbuffer_alloc,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_mob_rustbuffer_from_bytes,
    [ForeignBytes, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :ffi_mob_rustbuffer_free,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  attach_function :ffi_mob_rustbuffer_reserve,
    [RustBuffer.by_value, :uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  attach_function :uniffi_mob_checksum_method_client_attach_signer,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_execute_contract,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_get_account,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_get_all_balances,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_get_balance,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_get_chain_id,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_get_height,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_get_tx,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_is_synced,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_client_send,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_signer_address,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_signer_address_prefix,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_signer_public_key_hex,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_method_signer_sign_bytes,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_constructor_client_new,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_constructor_client_new_with_signer,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :uniffi_mob_checksum_constructor_signer_from_mnemonic,
    [RustCallStatus.by_ref],
    :uint16
  attach_function :ffi_mob_uniffi_contract_version,
    [RustCallStatus.by_ref],
    :uint32
  
end

  # Public interface members begin here.

  
  
  

class BroadcastMode
  SYNC = 1
  ASYNC = 2
  BLOCK = 3
  
end


  
  
  # Record type AccountInfo
class AccountInfo
  attr_reader :address, :account_number, :sequence, :pub_key

  def initialize(address:, account_number:, sequence:, pub_key:)
    @address = address
    @account_number = account_number
    @sequence = sequence
    @pub_key = pub_key
  end

  def ==(other)
    if @address != other.address
      return false
    end
    if @account_number != other.account_number
      return false
    end
    if @sequence != other.sequence
      return false
    end
    if @pub_key != other.pub_key
      return false
    end

    true
  end
end
  
  # Record type ChainConfig
class ChainConfig
  attr_reader :chain_id, :rpc_endpoint, :grpc_endpoint, :address_prefix, :coin_type, :gas_price

  def initialize(chain_id:, rpc_endpoint:, grpc_endpoint:, address_prefix:, coin_type:, gas_price:)
    @chain_id = chain_id
    @rpc_endpoint = rpc_endpoint
    @grpc_endpoint = grpc_endpoint
    @address_prefix = address_prefix
    @coin_type = coin_type
    @gas_price = gas_price
  end

  def ==(other)
    if @chain_id != other.chain_id
      return false
    end
    if @rpc_endpoint != other.rpc_endpoint
      return false
    end
    if @grpc_endpoint != other.grpc_endpoint
      return false
    end
    if @address_prefix != other.address_prefix
      return false
    end
    if @coin_type != other.coin_type
      return false
    end
    if @gas_price != other.gas_price
      return false
    end

    true
  end
end
  
  # Record type Coin
class Coin
  attr_reader :denom, :amount

  def initialize(denom:, amount:)
    @denom = denom
    @amount = amount
  end

  def ==(other)
    if @denom != other.denom
      return false
    end
    if @amount != other.amount
      return false
    end

    true
  end
end
  
  # Record type Fee
class Fee
  attr_reader :amount, :gas_limit, :payer, :granter

  def initialize(amount:, gas_limit:, payer:, granter:)
    @amount = amount
    @gas_limit = gas_limit
    @payer = payer
    @granter = granter
  end

  def ==(other)
    if @amount != other.amount
      return false
    end
    if @gas_limit != other.gas_limit
      return false
    end
    if @payer != other.payer
      return false
    end
    if @granter != other.granter
      return false
    end

    true
  end
end
  
  # Record type TxResponse
class TxResponse
  attr_reader :txhash, :code, :raw_log, :gas_wanted, :gas_used, :height

  def initialize(txhash:, code:, raw_log:, gas_wanted:, gas_used:, height:)
    @txhash = txhash
    @code = code
    @raw_log = raw_log
    @gas_wanted = gas_wanted
    @gas_used = gas_used
    @height = height
  end

  def ==(other)
    if @txhash != other.txhash
      return false
    end
    if @code != other.code
      return false
    end
    if @raw_log != other.raw_log
      return false
    end
    if @gas_wanted != other.gas_wanted
      return false
    end
    if @gas_used != other.gas_used
      return false
    end
    if @height != other.height
      return false
    end

    true
  end
end
  

  

  
  class Client

  # A private helper for initializing instances of the class from a raw handle,
  # bypassing any initialization logic and ensuring they are GC'd properly.
  def self.uniffi_allocate(handle)
    inst = allocate
    inst.instance_variable_set :@handle, handle
    ObjectSpace.define_finalizer(inst, uniffi_define_finalizer_by_handle(handle, inst.object_id))
    return inst
  end

  # A private helper for registering an object finalizer.
  # N.B. it's important that this does not capture a reference
  # to the actual instance, only its underlying handle.
  def self.uniffi_define_finalizer_by_handle(handle, object_id)
    Proc.new do |_id|
      Mob.rust_call(
        :uniffi_mob_fn_free_client,
        handle
      )
    end
  end

  # A private helper for lowering instances into a raw handle.
  # This does an explicit typecheck, because accidentally lowering a different type of
  # object in a place where this type is expected, could lead to memory unsafety.
  def self.uniffi_check_lower(inst)
    if not inst.is_a? self
      raise TypeError.new "Expected a Client instance, got #{inst}"
    end
  end

  def uniffi_clone_handle()
    return Mob.rust_call(
      :uniffi_mob_fn_clone_client,
      @handle
    )
  end

  def self.uniffi_lower(inst)
    return inst.uniffi_clone_handle()
  end
  def initialize(config)
        config = config
        RustBuffer.check_lower_TypeChainConfig(config)
    handle = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_constructor_client_new,RustBuffer.alloc_from_TypeChainConfig(config))
    @handle = handle
    ObjectSpace.define_finalizer(self, self.class.uniffi_define_finalizer_by_handle(handle, self.object_id))
  end

  def self.new_with_signer(config, signer)
        config = config
        RustBuffer.check_lower_TypeChainConfig(config)
        signer = signer
        (Signer.uniffi_check_lower signer)
    # Call the (fallible) function before creating any half-baked object instances.
    # Lightly yucky way to bypass the usual "initialize" logic
    # and just create a new instance with the required handle.
    return uniffi_allocate(Mob.rust_call_with_error(MobError,:uniffi_mob_fn_constructor_client_new_with_signer,RustBuffer.alloc_from_TypeChainConfig(config),(Signer.uniffi_lower signer)))
  end
  

  def attach_signer(signer)
        _signer = _signer
        (Signer.uniffi_check_lower _signer)
      Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_attach_signer,uniffi_clone_handle(),(Signer.uniffi_lower _signer))
  end
  
  def execute_contract(contract_address, msg, funds, memo)
        contract_address = Mob::uniffi_utf8(contract_address)
        
        msg = Mob::uniffi_bytes(msg)
        
        funds = funds
        RustBuffer.check_lower_SequenceTypeCoin(funds)
        memo = (memo ? Mob::uniffi_utf8(memo) : nil)
        RustBuffer.check_lower_Optionalstring(memo)
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_execute_contract,uniffi_clone_handle(),RustBuffer.allocFromString(contract_address),RustBuffer.allocFromBytes(msg),RustBuffer.alloc_from_SequenceTypeCoin(funds),RustBuffer.alloc_from_Optionalstring(memo))
    return result.consumeIntoTypeTxResponse
  end
  def get_account(address)
        address = Mob::uniffi_utf8(address)
        
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_get_account,uniffi_clone_handle(),RustBuffer.allocFromString(address))
    return result.consumeIntoTypeAccountInfo
  end
  def get_all_balances(address)
        address = Mob::uniffi_utf8(address)
        
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_get_all_balances,uniffi_clone_handle(),RustBuffer.allocFromString(address))
    return result.consumeIntoSequenceTypeCoin
  end
  def get_balance(address, denom)
        address = Mob::uniffi_utf8(address)
        
        denom = Mob::uniffi_utf8(denom)
        
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_get_balance,uniffi_clone_handle(),RustBuffer.allocFromString(address),RustBuffer.allocFromString(denom))
    return result.consumeIntoTypeCoin
  end
  def get_chain_id()
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_get_chain_id,uniffi_clone_handle(),)
    return result.consumeIntoString
  end
  def get_height()
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_get_height,uniffi_clone_handle(),)
    return result.to_i
  end
  def get_tx(hash)
        hash = Mob::uniffi_utf8(hash)
        
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_get_tx,uniffi_clone_handle(),RustBuffer.allocFromString(hash))
    return result.consumeIntoTypeTxResponse
  end
  def is_synced()
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_is_synced,uniffi_clone_handle(),)
    return 1 == result
  end
  def send(to_address, amount, memo)
        to_address = Mob::uniffi_utf8(to_address)
        
        amount = amount
        RustBuffer.check_lower_SequenceTypeCoin(amount)
        memo = (memo ? Mob::uniffi_utf8(memo) : nil)
        RustBuffer.check_lower_Optionalstring(memo)
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_client_send,uniffi_clone_handle(),RustBuffer.allocFromString(to_address),RustBuffer.alloc_from_SequenceTypeCoin(amount),RustBuffer.alloc_from_Optionalstring(memo))
    return result.consumeIntoTypeTxResponse
  end
  
end
  
  class Signer

  # A private helper for initializing instances of the class from a raw handle,
  # bypassing any initialization logic and ensuring they are GC'd properly.
  def self.uniffi_allocate(handle)
    inst = allocate
    inst.instance_variable_set :@handle, handle
    ObjectSpace.define_finalizer(inst, uniffi_define_finalizer_by_handle(handle, inst.object_id))
    return inst
  end

  # A private helper for registering an object finalizer.
  # N.B. it's important that this does not capture a reference
  # to the actual instance, only its underlying handle.
  def self.uniffi_define_finalizer_by_handle(handle, object_id)
    Proc.new do |_id|
      Mob.rust_call(
        :uniffi_mob_fn_free_signer,
        handle
      )
    end
  end

  # A private helper for lowering instances into a raw handle.
  # This does an explicit typecheck, because accidentally lowering a different type of
  # object in a place where this type is expected, could lead to memory unsafety.
  def self.uniffi_check_lower(inst)
    if not inst.is_a? self
      raise TypeError.new "Expected a Signer instance, got #{inst}"
    end
  end

  def uniffi_clone_handle()
    return Mob.rust_call(
      :uniffi_mob_fn_clone_signer,
      @handle
    )
  end

  def self.uniffi_lower(inst)
    return inst.uniffi_clone_handle()
  end

  def self.from_mnemonic(mnemonic, address_prefix, derivation_path)
        mnemonic = Mob::uniffi_utf8(mnemonic)
        
        address_prefix = Mob::uniffi_utf8(address_prefix)
        
        derivation_path = (derivation_path ? Mob::uniffi_utf8(derivation_path) : nil)
        RustBuffer.check_lower_Optionalstring(derivation_path)
    # Call the (fallible) function before creating any half-baked object instances.
    # Lightly yucky way to bypass the usual "initialize" logic
    # and just create a new instance with the required handle.
    return uniffi_allocate(Mob.rust_call_with_error(MobError,:uniffi_mob_fn_constructor_signer_from_mnemonic,RustBuffer.allocFromString(mnemonic),RustBuffer.allocFromString(address_prefix),RustBuffer.alloc_from_Optionalstring(derivation_path)))
  end
  

  def address()
    result = Mob.rust_call(:uniffi_mob_fn_method_signer_address,uniffi_clone_handle(),)
    return result.consumeIntoString
  end
  def address_prefix()
    result = Mob.rust_call(:uniffi_mob_fn_method_signer_address_prefix,uniffi_clone_handle(),)
    return result.consumeIntoString
  end
  def public_key_hex()
    result = Mob.rust_call(:uniffi_mob_fn_method_signer_public_key_hex,uniffi_clone_handle(),)
    return result.consumeIntoString
  end
  def sign_bytes(message)
        message = Mob::uniffi_bytes(message)
        
    result = Mob.rust_call_with_error(MobError,:uniffi_mob_fn_method_signer_sign_bytes,uniffi_clone_handle(),RustBuffer.allocFromBytes(message))
    return result.consumeIntoBytes
  end
  
end
  
end

