# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_mob_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_mob_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_mob_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("mob")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_mob_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_mob_checksum_constructor_client_new() != 24379:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_constructor_client_new_with_signer() != 15565:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_attach_signer() != 52997:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_execute_contract() != 63353:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_get_account() != 2621:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_get_all_balances() != 43366:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_get_balance() != 52124:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_get_chain_id() != 7648:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_get_height() != 45521:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_get_tx() != 58481:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_is_synced() != 61050:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_client_send() != 9214:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_constructor_signer_from_mnemonic() != 23747:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_signer_address() != 11665:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_signer_address_prefix() != 17461:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_signer_public_key_hex() != 30197:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_mob_checksum_method_signer_sign_bytes() != 10133:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_mob_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_mob_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_mob_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rustbuffer_free.restype = None
_UniffiLib.ffi_mob_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rustbuffer_reserve.restype = _UniffiRustBuffer
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFutureDroppedCallbackStruct(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK),
    ]
_UniffiLib.ffi_mob_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_u8.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_mob_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_mob_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_u8.restype = None
_UniffiLib.ffi_mob_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_i8.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_mob_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_mob_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_i8.restype = None
_UniffiLib.ffi_mob_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_u16.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_mob_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_mob_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_u16.restype = None
_UniffiLib.ffi_mob_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_i16.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_mob_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_mob_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_i16.restype = None
_UniffiLib.ffi_mob_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_u32.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_mob_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_mob_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_u32.restype = None
_UniffiLib.ffi_mob_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_i32.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_mob_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_mob_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_i32.restype = None
_UniffiLib.ffi_mob_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_u64.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_mob_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_mob_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_u64.restype = None
_UniffiLib.ffi_mob_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_i64.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_mob_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_mob_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_i64.restype = None
_UniffiLib.ffi_mob_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_f32.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_mob_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_mob_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_f32.restype = None
_UniffiLib.ffi_mob_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_f64.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_mob_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_mob_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_f64.restype = None
_UniffiLib.ffi_mob_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_mob_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_mob_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_mob_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_poll_void.restype = None
_UniffiLib.ffi_mob_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_cancel_void.restype = None
_UniffiLib.ffi_mob_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_mob_rust_future_complete_void.restype = None
_UniffiLib.ffi_mob_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_mob_rust_future_free_void.restype = None
_UniffiLib.uniffi_mob_fn_clone_client.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_clone_client.restype = ctypes.c_uint64
_UniffiLib.uniffi_mob_fn_free_client.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_free_client.restype = None
_UniffiLib.uniffi_mob_fn_clone_signer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_clone_signer.restype = ctypes.c_uint64
_UniffiLib.uniffi_mob_fn_free_signer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_free_signer.restype = None
_UniffiLib.uniffi_mob_fn_constructor_client_new.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_constructor_client_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_mob_fn_constructor_client_new_with_signer.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_constructor_client_new_with_signer.restype = ctypes.c_uint64
_UniffiLib.uniffi_mob_fn_method_client_attach_signer.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_attach_signer.restype = None
_UniffiLib.uniffi_mob_fn_method_client_execute_contract.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_execute_contract.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_client_get_account.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_get_account.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_client_get_all_balances.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_get_all_balances.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_client_get_balance.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_get_balance.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_client_get_chain_id.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_get_chain_id.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_client_get_height.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_get_height.restype = ctypes.c_uint64
_UniffiLib.uniffi_mob_fn_method_client_get_tx.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_get_tx.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_client_is_synced.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_is_synced.restype = ctypes.c_int8
_UniffiLib.uniffi_mob_fn_method_client_send.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_client_send.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_constructor_signer_from_mnemonic.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_constructor_signer_from_mnemonic.restype = ctypes.c_uint64
_UniffiLib.uniffi_mob_fn_method_signer_address.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_signer_address.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_signer_address_prefix.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_signer_address_prefix.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_signer_public_key_hex.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_signer_public_key_hex.restype = _UniffiRustBuffer
_UniffiLib.uniffi_mob_fn_method_signer_sign_bytes.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_mob_fn_method_signer_sign_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_mob_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_mob_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_mob_checksum_constructor_client_new.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_constructor_client_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_constructor_client_new_with_signer.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_constructor_client_new_with_signer.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_attach_signer.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_attach_signer.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_execute_contract.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_execute_contract.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_get_account.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_get_account.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_get_all_balances.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_get_all_balances.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_get_balance.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_get_balance.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_get_chain_id.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_get_chain_id.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_get_height.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_get_height.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_get_tx.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_get_tx.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_is_synced.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_is_synced.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_client_send.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_client_send.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_constructor_signer_from_mnemonic.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_constructor_signer_from_mnemonic.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_signer_address.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_signer_address.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_signer_address_prefix.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_signer_address_prefix.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_signer_public_key_hex.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_signer_public_key_hex.restype = ctypes.c_uint16
_UniffiLib.uniffi_mob_checksum_method_signer_sign_bytes.argtypes = (
)
_UniffiLib.uniffi_mob_checksum_method_signer_sign_bytes.restype = ctypes.c_uint16

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class AccountInfo:
    """
    Account information
"""
    def __init__(self, *, address:str, account_number:int, sequence:int, pub_key:typing.Optional[str]):
        self.address = address
        self.account_number = account_number
        self.sequence = sequence
        self.pub_key = pub_key
        
        

    
    def __str__(self):
        return "AccountInfo(address={}, account_number={}, sequence={}, pub_key={})".format(self.address, self.account_number, self.sequence, self.pub_key)
    def __eq__(self, other):
        if self.address != other.address:
            return False
        if self.account_number != other.account_number:
            return False
        if self.sequence != other.sequence:
            return False
        if self.pub_key != other.pub_key:
            return False
        return True

class _UniffiFfiConverterTypeAccountInfo(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return AccountInfo(
            address=_UniffiFfiConverterString.read(buf),
            account_number=_UniffiFfiConverterUInt64.read(buf),
            sequence=_UniffiFfiConverterUInt64.read(buf),
            pub_key=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.address)
        _UniffiFfiConverterUInt64.check_lower(value.account_number)
        _UniffiFfiConverterUInt64.check_lower(value.sequence)
        _UniffiFfiConverterOptionalString.check_lower(value.pub_key)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.address, buf)
        _UniffiFfiConverterUInt64.write(value.account_number, buf)
        _UniffiFfiConverterUInt64.write(value.sequence, buf)
        _UniffiFfiConverterOptionalString.write(value.pub_key, buf)

class _UniffiFfiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)

@dataclass
class ChainConfig:
    """
    Chain configuration
"""
    def __init__(self, *, chain_id:str, rpc_endpoint:str, grpc_endpoint:typing.Optional[str], address_prefix:str, coin_type:int, gas_price:str):
        self.chain_id = chain_id
        self.rpc_endpoint = rpc_endpoint
        self.grpc_endpoint = grpc_endpoint
        self.address_prefix = address_prefix
        self.coin_type = coin_type
        self.gas_price = gas_price
        
        

    
    def __str__(self):
        return "ChainConfig(chain_id={}, rpc_endpoint={}, grpc_endpoint={}, address_prefix={}, coin_type={}, gas_price={})".format(self.chain_id, self.rpc_endpoint, self.grpc_endpoint, self.address_prefix, self.coin_type, self.gas_price)
    def __eq__(self, other):
        if self.chain_id != other.chain_id:
            return False
        if self.rpc_endpoint != other.rpc_endpoint:
            return False
        if self.grpc_endpoint != other.grpc_endpoint:
            return False
        if self.address_prefix != other.address_prefix:
            return False
        if self.coin_type != other.coin_type:
            return False
        if self.gas_price != other.gas_price:
            return False
        return True

class _UniffiFfiConverterTypeChainConfig(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ChainConfig(
            chain_id=_UniffiFfiConverterString.read(buf),
            rpc_endpoint=_UniffiFfiConverterString.read(buf),
            grpc_endpoint=_UniffiFfiConverterOptionalString.read(buf),
            address_prefix=_UniffiFfiConverterString.read(buf),
            coin_type=_UniffiFfiConverterUInt32.read(buf),
            gas_price=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.chain_id)
        _UniffiFfiConverterString.check_lower(value.rpc_endpoint)
        _UniffiFfiConverterOptionalString.check_lower(value.grpc_endpoint)
        _UniffiFfiConverterString.check_lower(value.address_prefix)
        _UniffiFfiConverterUInt32.check_lower(value.coin_type)
        _UniffiFfiConverterString.check_lower(value.gas_price)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.chain_id, buf)
        _UniffiFfiConverterString.write(value.rpc_endpoint, buf)
        _UniffiFfiConverterOptionalString.write(value.grpc_endpoint, buf)
        _UniffiFfiConverterString.write(value.address_prefix, buf)
        _UniffiFfiConverterUInt32.write(value.coin_type, buf)
        _UniffiFfiConverterString.write(value.gas_price, buf)

@dataclass
class Coin:
    """
    Represents a coin amount with denomination
"""
    def __init__(self, *, denom:str, amount:str):
        self.denom = denom
        self.amount = amount
        
        

    
    def __str__(self):
        return "Coin(denom={}, amount={})".format(self.denom, self.amount)
    def __eq__(self, other):
        if self.denom != other.denom:
            return False
        if self.amount != other.amount:
            return False
        return True

class _UniffiFfiConverterTypeCoin(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Coin(
            denom=_UniffiFfiConverterString.read(buf),
            amount=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.denom)
        _UniffiFfiConverterString.check_lower(value.amount)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.denom, buf)
        _UniffiFfiConverterString.write(value.amount, buf)

class _UniffiFfiConverterSequenceTypeCoin(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeCoin.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeCoin.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeCoin.read(buf) for i in range(count)
        ]

@dataclass
class Fee:
    """
    Transaction fee information
"""
    def __init__(self, *, amount:typing.List[Coin], gas_limit:int, payer:typing.Optional[str], granter:typing.Optional[str]):
        self.amount = amount
        self.gas_limit = gas_limit
        self.payer = payer
        self.granter = granter
        
        

    
    def __str__(self):
        return "Fee(amount={}, gas_limit={}, payer={}, granter={})".format(self.amount, self.gas_limit, self.payer, self.granter)
    def __eq__(self, other):
        if self.amount != other.amount:
            return False
        if self.gas_limit != other.gas_limit:
            return False
        if self.payer != other.payer:
            return False
        if self.granter != other.granter:
            return False
        return True

class _UniffiFfiConverterTypeFee(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Fee(
            amount=_UniffiFfiConverterSequenceTypeCoin.read(buf),
            gas_limit=_UniffiFfiConverterUInt64.read(buf),
            payer=_UniffiFfiConverterOptionalString.read(buf),
            granter=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceTypeCoin.check_lower(value.amount)
        _UniffiFfiConverterUInt64.check_lower(value.gas_limit)
        _UniffiFfiConverterOptionalString.check_lower(value.payer)
        _UniffiFfiConverterOptionalString.check_lower(value.granter)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceTypeCoin.write(value.amount, buf)
        _UniffiFfiConverterUInt64.write(value.gas_limit, buf)
        _UniffiFfiConverterOptionalString.write(value.payer, buf)
        _UniffiFfiConverterOptionalString.write(value.granter, buf)

class _UniffiFfiConverterInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i64"
    VALUE_MIN = -2**63
    VALUE_MAX = 2**63

    @staticmethod
    def read(buf):
        return buf.read_i64()

    @staticmethod
    def write(value, buf):
        buf.write_i64(value)

@dataclass
class TxResponse:
    """
    Transaction response
"""
    def __init__(self, *, txhash:str, code:int, raw_log:str, gas_wanted:int, gas_used:int, height:int):
        self.txhash = txhash
        self.code = code
        self.raw_log = raw_log
        self.gas_wanted = gas_wanted
        self.gas_used = gas_used
        self.height = height
        
        

    
    def __str__(self):
        return "TxResponse(txhash={}, code={}, raw_log={}, gas_wanted={}, gas_used={}, height={})".format(self.txhash, self.code, self.raw_log, self.gas_wanted, self.gas_used, self.height)
    def __eq__(self, other):
        if self.txhash != other.txhash:
            return False
        if self.code != other.code:
            return False
        if self.raw_log != other.raw_log:
            return False
        if self.gas_wanted != other.gas_wanted:
            return False
        if self.gas_used != other.gas_used:
            return False
        if self.height != other.height:
            return False
        return True

class _UniffiFfiConverterTypeTxResponse(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return TxResponse(
            txhash=_UniffiFfiConverterString.read(buf),
            code=_UniffiFfiConverterUInt32.read(buf),
            raw_log=_UniffiFfiConverterString.read(buf),
            gas_wanted=_UniffiFfiConverterUInt64.read(buf),
            gas_used=_UniffiFfiConverterUInt64.read(buf),
            height=_UniffiFfiConverterInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.txhash)
        _UniffiFfiConverterUInt32.check_lower(value.code)
        _UniffiFfiConverterString.check_lower(value.raw_log)
        _UniffiFfiConverterUInt64.check_lower(value.gas_wanted)
        _UniffiFfiConverterUInt64.check_lower(value.gas_used)
        _UniffiFfiConverterInt64.check_lower(value.height)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.txhash, buf)
        _UniffiFfiConverterUInt32.write(value.code, buf)
        _UniffiFfiConverterString.write(value.raw_log, buf)
        _UniffiFfiConverterUInt64.write(value.gas_wanted, buf)
        _UniffiFfiConverterUInt64.write(value.gas_used, buf)
        _UniffiFfiConverterInt64.write(value.height, buf)






class BroadcastMode(enum.Enum):
    """
    Broadcast mode for transactions
"""
    
    SYNC = 0
    """
    Synchronous - returns after CheckTx
"""
    
    ASYNC = 1
    """
    Asynchronous - returns immediately
"""
    
    BLOCK = 2
    """
    Block - waits until transaction is included in a block
"""
    


class _UniffiFfiConverterTypeBroadcastMode(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return BroadcastMode.SYNC
        if variant == 2:
            return BroadcastMode.ASYNC
        if variant == 3:
            return BroadcastMode.BLOCK
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == BroadcastMode.SYNC:
            return
        if value == BroadcastMode.ASYNC:
            return
        if value == BroadcastMode.BLOCK:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == BroadcastMode.SYNC:
            buf.write_i32(1)
        if value == BroadcastMode.ASYNC:
            buf.write_i32(2)
        if value == BroadcastMode.BLOCK:
            buf.write_i32(3)





# MobError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class MobError(Exception):
    """
    Main error type for the mob library
"""
    pass

_UniffiTempMobError = MobError

class MobError:  # type: ignore
    """
    Main error type for the mob library
"""
    
    class Rpc(_UniffiTempMobError):
        """
        RPC-related errors
"""
        def __repr__(self):
            return "MobError.Rpc({})".format(repr(str(self)))
    _UniffiTempMobError.Rpc = Rpc # type: ignore
    class Transaction(_UniffiTempMobError):
        """
        Transaction-related errors
"""
        def __repr__(self):
            return "MobError.Transaction({})".format(repr(str(self)))
    _UniffiTempMobError.Transaction = Transaction # type: ignore
    class Signing(_UniffiTempMobError):
        """
        Signing-related errors
"""
        def __repr__(self):
            return "MobError.Signing({})".format(repr(str(self)))
    _UniffiTempMobError.Signing = Signing # type: ignore
    class KeyDerivation(_UniffiTempMobError):
        """
        Key derivation errors
"""
        def __repr__(self):
            return "MobError.KeyDerivation({})".format(repr(str(self)))
    _UniffiTempMobError.KeyDerivation = KeyDerivation # type: ignore
    class Address(_UniffiTempMobError):
        """
        Address parsing/generation errors
"""
        def __repr__(self):
            return "MobError.Address({})".format(repr(str(self)))
    _UniffiTempMobError.Address = Address # type: ignore
    class Serialization(_UniffiTempMobError):
        """
        Serialization/deserialization errors
"""
        def __repr__(self):
            return "MobError.Serialization({})".format(repr(str(self)))
    _UniffiTempMobError.Serialization = Serialization # type: ignore
    class InvalidInput(_UniffiTempMobError):
        """
        Invalid input errors
"""
        def __repr__(self):
            return "MobError.InvalidInput({})".format(repr(str(self)))
    _UniffiTempMobError.InvalidInput = InvalidInput # type: ignore
    class Account(_UniffiTempMobError):
        """
        Account-related errors
"""
        def __repr__(self):
            return "MobError.Account({})".format(repr(str(self)))
    _UniffiTempMobError.Account = Account # type: ignore
    class Network(_UniffiTempMobError):
        """
        Network-related errors
"""
        def __repr__(self):
            return "MobError.Network({})".format(repr(str(self)))
    _UniffiTempMobError.Network = Network # type: ignore
    class GasEstimation(_UniffiTempMobError):
        """
        Gas estimation errors
"""
        def __repr__(self):
            return "MobError.GasEstimation({})".format(repr(str(self)))
    _UniffiTempMobError.GasEstimation = GasEstimation # type: ignore
    class InsufficientFunds(_UniffiTempMobError):
        """
        Insufficient funds
"""
        def __repr__(self):
            return "MobError.InsufficientFunds({})".format(repr(str(self)))
    _UniffiTempMobError.InsufficientFunds = InsufficientFunds # type: ignore
    class Timeout(_UniffiTempMobError):
        """
        Timeout errors
"""
        def __repr__(self):
            return "MobError.Timeout({})".format(repr(str(self)))
    _UniffiTempMobError.Timeout = Timeout # type: ignore
    class Generic(_UniffiTempMobError):
        """
        Generic error
"""
        def __repr__(self):
            return "MobError.Generic({})".format(repr(str(self)))
    _UniffiTempMobError.Generic = Generic # type: ignore

MobError = _UniffiTempMobError # type: ignore
del _UniffiTempMobError


class _UniffiFfiConverterTypeMobError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return MobError.Rpc(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return MobError.Transaction(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return MobError.Signing(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return MobError.KeyDerivation(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return MobError.Address(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 6:
            return MobError.Serialization(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 7:
            return MobError.InvalidInput(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 8:
            return MobError.Account(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 9:
            return MobError.Network(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 10:
            return MobError.GasEstimation(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 11:
            return MobError.InsufficientFunds(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 12:
            return MobError.Timeout(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 13:
            return MobError.Generic(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, MobError.Rpc):
            return
        if isinstance(value, MobError.Transaction):
            return
        if isinstance(value, MobError.Signing):
            return
        if isinstance(value, MobError.KeyDerivation):
            return
        if isinstance(value, MobError.Address):
            return
        if isinstance(value, MobError.Serialization):
            return
        if isinstance(value, MobError.InvalidInput):
            return
        if isinstance(value, MobError.Account):
            return
        if isinstance(value, MobError.Network):
            return
        if isinstance(value, MobError.GasEstimation):
            return
        if isinstance(value, MobError.InsufficientFunds):
            return
        if isinstance(value, MobError.Timeout):
            return
        if isinstance(value, MobError.Generic):
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, MobError.Rpc):
            buf.write_i32(1)
        if isinstance(value, MobError.Transaction):
            buf.write_i32(2)
        if isinstance(value, MobError.Signing):
            buf.write_i32(3)
        if isinstance(value, MobError.KeyDerivation):
            buf.write_i32(4)
        if isinstance(value, MobError.Address):
            buf.write_i32(5)
        if isinstance(value, MobError.Serialization):
            buf.write_i32(6)
        if isinstance(value, MobError.InvalidInput):
            buf.write_i32(7)
        if isinstance(value, MobError.Account):
            buf.write_i32(8)
        if isinstance(value, MobError.Network):
            buf.write_i32(9)
        if isinstance(value, MobError.GasEstimation):
            buf.write_i32(10)
        if isinstance(value, MobError.InsufficientFunds):
            buf.write_i32(11)
        if isinstance(value, MobError.Timeout):
            buf.write_i32(12)
        if isinstance(value, MobError.Generic):
            buf.write_i32(13)

class _UniffiFfiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)


class SignerProtocol(typing.Protocol):
    """
    A signer that manages keys and can sign transactions
"""
    
    def address(self, ) -> str:
        """
        Get the signer's address
"""
        raise NotImplementedError
    def address_prefix(self, ) -> str:
        """
        Get the address prefix
"""
        raise NotImplementedError
    def public_key_hex(self, ) -> str:
        """
        Get the signer's public key as hex
"""
        raise NotImplementedError
    def sign_bytes(self, message: bytes) -> bytes:
        """
        Sign arbitrary bytes
"""
        raise NotImplementedError

class Signer(SignerProtocol):
    """
    A signer that manages keys and can sign transactions
"""
    
    _handle: ctypes.c_uint64
    @classmethod
    def from_mnemonic(cls, mnemonic: str,address_prefix: str,derivation_path: typing.Optional[str]) -> Signer:
        """
        Create a new signer from a mnemonic phrase
"""
        
        _UniffiFfiConverterString.check_lower(mnemonic)
        
        _UniffiFfiConverterString.check_lower(address_prefix)
        
        _UniffiFfiConverterOptionalString.check_lower(derivation_path)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(mnemonic),
            _UniffiFfiConverterString.lower(address_prefix),
            _UniffiFfiConverterOptionalString.lower(derivation_path),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeSigner.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_constructor_signer_from_mnemonic,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_mob_fn_free_signer, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_mob_fn_clone_signer, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def address(self, ) -> str:
        """
        Get the signer's address
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_signer_address,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def address_prefix(self, ) -> str:
        """
        Get the address prefix
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_signer_address_prefix,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def public_key_hex(self, ) -> str:
        """
        Get the signer's public key as hex
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_signer_public_key_hex,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def sign_bytes(self, message: bytes) -> bytes:
        """
        Sign arbitrary bytes
"""
        
        _UniffiFfiConverterBytes.check_lower(message)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterBytes.lower(message),
        )
        _uniffi_lift_return = _UniffiFfiConverterBytes.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_signer_sign_bytes,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeSigner:
    @staticmethod
    def lift(value: int) -> Signer:
        return Signer._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: Signer):
        if not isinstance(value, Signer):
            raise TypeError("Expected Signer instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: Signer) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> Signer:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: Signer, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)


class ClientProtocol(typing.Protocol):
    """
    RPC client for interacting with the blockchain
"""
    
    def attach_signer(self, signer: Signer) -> None:
        """
        Attach a signer to the client
"""
        raise NotImplementedError
    def execute_contract(self, contract_address: str,msg: bytes,funds: typing.List[Coin],memo: typing.Optional[str]) -> TxResponse:
        """
        Execute a CosmWasm contract (synchronous wrapper)
"""
        raise NotImplementedError
    def get_account(self, address: str) -> AccountInfo:
        """
        Query account information (synchronous wrapper)
"""
        raise NotImplementedError
    def get_all_balances(self, address: str) -> typing.List[Coin]:
        """
        Query all balances for an address (synchronous wrapper)
"""
        raise NotImplementedError
    def get_balance(self, address: str,denom: str) -> Coin:
        """
        Query account balance (synchronous wrapper)
"""
        raise NotImplementedError
    def get_chain_id(self, ) -> str:
        """
        Get chain ID (synchronous wrapper)
"""
        raise NotImplementedError
    def get_height(self, ) -> int:
        """
        Get the latest block height (synchronous wrapper)
"""
        raise NotImplementedError
    def get_tx(self, hash: str) -> TxResponse:
        """
        Query transaction by hash (synchronous wrapper)
"""
        raise NotImplementedError
    def is_synced(self, ) -> bool:
        """
        Check if the node is synced (synchronous wrapper)
"""
        raise NotImplementedError
    def send(self, to_address: str,amount: typing.List[Coin],memo: typing.Optional[str]) -> TxResponse:
        """
        Send tokens to a recipient (synchronous wrapper)
"""
        raise NotImplementedError

class Client(ClientProtocol):
    """
    RPC client for interacting with the blockchain
"""
    
    _handle: ctypes.c_uint64
    def __init__(self, config: ChainConfig):
        """
        Create a new RPC client (synchronous wrapper for FFI)
"""
        
        _UniffiFfiConverterTypeChainConfig.check_lower(config)
        _uniffi_lowered_args = (
            _UniffiFfiConverterTypeChainConfig.lower(config),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeClient.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_constructor_client_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result
    @classmethod
    def new_with_signer(cls, config: ChainConfig,signer: Signer) -> Client:
        """
        Create a new RPC client with a signer attached (synchronous wrapper for FFI)
"""
        
        _UniffiFfiConverterTypeChainConfig.check_lower(config)
        
        _UniffiFfiConverterTypeSigner.check_lower(signer)
        _uniffi_lowered_args = (
            _UniffiFfiConverterTypeChainConfig.lower(config),
            _UniffiFfiConverterTypeSigner.lower(signer),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeClient.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_constructor_client_new_with_signer,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_mob_fn_free_client, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_mob_fn_clone_client, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def attach_signer(self, signer: Signer) -> None:
        """
        Attach a signer to the client
"""
        
        _UniffiFfiConverterTypeSigner.check_lower(signer)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterTypeSigner.lower(signer),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_attach_signer,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def execute_contract(self, contract_address: str,msg: bytes,funds: typing.List[Coin],memo: typing.Optional[str]) -> TxResponse:
        """
        Execute a CosmWasm contract (synchronous wrapper)
"""
        
        _UniffiFfiConverterString.check_lower(contract_address)
        
        _UniffiFfiConverterBytes.check_lower(msg)
        
        _UniffiFfiConverterSequenceTypeCoin.check_lower(funds)
        
        _UniffiFfiConverterOptionalString.check_lower(memo)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(contract_address),
            _UniffiFfiConverterBytes.lower(msg),
            _UniffiFfiConverterSequenceTypeCoin.lower(funds),
            _UniffiFfiConverterOptionalString.lower(memo),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeTxResponse.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_execute_contract,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_account(self, address: str) -> AccountInfo:
        """
        Query account information (synchronous wrapper)
"""
        
        _UniffiFfiConverterString.check_lower(address)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(address),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeAccountInfo.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_get_account,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_all_balances(self, address: str) -> typing.List[Coin]:
        """
        Query all balances for an address (synchronous wrapper)
"""
        
        _UniffiFfiConverterString.check_lower(address)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(address),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceTypeCoin.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_get_all_balances,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_balance(self, address: str,denom: str) -> Coin:
        """
        Query account balance (synchronous wrapper)
"""
        
        _UniffiFfiConverterString.check_lower(address)
        
        _UniffiFfiConverterString.check_lower(denom)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(address),
            _UniffiFfiConverterString.lower(denom),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeCoin.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_get_balance,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_chain_id(self, ) -> str:
        """
        Get chain ID (synchronous wrapper)
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_get_chain_id,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_height(self, ) -> int:
        """
        Get the latest block height (synchronous wrapper)
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_get_height,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_tx(self, hash: str) -> TxResponse:
        """
        Query transaction by hash (synchronous wrapper)
"""
        
        _UniffiFfiConverterString.check_lower(hash)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(hash),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeTxResponse.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_get_tx,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def is_synced(self, ) -> bool:
        """
        Check if the node is synced (synchronous wrapper)
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_is_synced,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def send(self, to_address: str,amount: typing.List[Coin],memo: typing.Optional[str]) -> TxResponse:
        """
        Send tokens to a recipient (synchronous wrapper)
"""
        
        _UniffiFfiConverterString.check_lower(to_address)
        
        _UniffiFfiConverterSequenceTypeCoin.check_lower(amount)
        
        _UniffiFfiConverterOptionalString.check_lower(memo)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(to_address),
            _UniffiFfiConverterSequenceTypeCoin.lower(amount),
            _UniffiFfiConverterOptionalString.lower(memo),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeTxResponse.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeMobError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_mob_fn_method_client_send,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeClient:
    @staticmethod
    def lift(value: int) -> Client:
        return Client._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: Client):
        if not isinstance(value, Client):
            raise TypeError("Expected Client instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: Client) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> Client:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: Client, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

__all__ = [
    "InternalError",
    "BroadcastMode",
    "MobError",
    "AccountInfo",
    "ChainConfig",
    "Coin",
    "Fee",
    "TxResponse",
    "Signer",
    "SignerProtocol",
    "Client",
    "ClientProtocol",
]