"""
Python Custom Signer Example

This example demonstrates how to implement a custom cryptographic signer in Python
that uses Python's cryptography library instead of the built-in Rust implementation.

This allows you to:
- Use Python's native cryptographic libraries
- Integrate with hardware wallets or HSMs
- Use platform-specific secure enclaves
- Implement custom key management strategies
"""

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.backends import default_backend
import hashlib
import bech32

# Import the mob library (generated by UniFFI)
from mob import CryptoSigner, SignerError, Client, ChainConfig, Coin


class PythonCryptoSigner(CryptoSigner):
    """
    Custom cryptographic signer implemented in Python using the cryptography library.

    This class implements the CryptoSigner trait defined in Rust, allowing
    the mob library to use Python's cryptographic implementations.
    """

    def __init__(self, private_key_bytes: bytes, address_prefix: str):
        """
        Initialize the signer with a private key.

        Args:
            private_key_bytes: 32-byte secp256k1 private key
            address_prefix: Bech32 address prefix (e.g., "xion")
        """
        # Load the private key using Python's cryptography library
        self._private_key = ec.derive_private_key(
            int.from_bytes(private_key_bytes, byteorder='big'),
            ec.SECP256K1(),
            default_backend()
        )

        # Get the public key in compressed format (33 bytes)
        self._public_key = self._private_key.public_key().public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.CompressedPoint
        )

        self._address_prefix = address_prefix

        # Generate the address from the public key
        self._address = self._generate_address()

    def _generate_address(self) -> str:
        """Generate a bech32 address from the public key."""
        # SHA256 hash of the public key
        sha256_hash = hashlib.sha256(self._public_key).digest()

        # RIPEMD160 hash of the SHA256 hash
        ripemd160 = hashlib.new('ripemd160')
        ripemd160.update(sha256_hash)
        address_bytes = ripemd160.digest()

        # Convert to bech32 format
        converted = bech32.convertbits(address_bytes, 8, 5)
        return bech32.bech32_encode(self._address_prefix, converted)

    def address(self) -> str:
        """Get the signer's bech32 address."""
        return self._address

    def public_key(self) -> bytes:
        """
        Get the signer's compressed secp256k1 public key.

        Returns:
            33-byte compressed public key (0x02/0x03 prefix + 32-byte X coordinate)
        """
        return self._public_key

    def address_prefix(self) -> str:
        """Get the address prefix (e.g., 'xion')."""
        return self._address_prefix

    def sign_bytes(self, message: bytes) -> bytes:
        """
        Sign arbitrary bytes with secp256k1 ECDSA.

        Args:
            message: The message bytes to sign

        Returns:
            64-byte signature in format: r (32 bytes) || s (32 bytes)
            The signature is normalized to low-S form as required by Cosmos SDK.
        """
        try:
            # Hash the message with SHA256 (as required by Cosmos)
            message_hash = hashlib.sha256(message).digest()

            # Sign the hash using Python's cryptography library
            signature = self._private_key.sign(
                message_hash,
                ec.ECDSA(hashes.SHA256())  # Already hashed, but required by API
            )

            # Extract r and s from DER-encoded signature
            # The signature is in DER format, we need to extract r and s
            from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
            r, s = decode_dss_signature(signature)

            # Normalize to low-S form (required by Cosmos SDK)
            # secp256k1 curve order
            n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
            if s > n // 2:
                s = n - s

            # Convert r and s to 32-byte big-endian format
            r_bytes = r.to_bytes(32, byteorder='big')
            s_bytes = s.to_bytes(32, byteorder='big')

            # Return concatenated r || s (64 bytes total)
            return r_bytes + s_bytes

        except Exception as e:
            raise SignerError.SigningFailed(f"Failed to sign message: {str(e)}")


def example_usage():
    """
    Example showing how to use the Python custom signer with the mob library.
    """
    # Generate or load a private key (32 bytes)
    # In production, load this securely from a keystore, HSM, etc.
    private_key = bytes.fromhex("your_private_key_hex_here")

    # Create the Python-based signer
    signer = PythonCryptoSigner(private_key, "xion")

    print(f"Address: {signer.address()}")
    print(f"Public Key: {signer.public_key().hex()}")

    # Create a mob client
    config = ChainConfig.new(
        "xion-testnet-1",
        "https://rpc.xion-testnet-1.burnt.com:443",
        "xion"
    )

    client = Client.new_with_signer(config, signer)

    # Now you can use the client with your custom Python signer!
    # The client will call your Python implementation for all signing operations

    # Send tokens using the Python signer
    response = client.send(
        "xion1recipient...",
        [Coin.new("uxion", "1000000")],
        "Transfer using Python signer"
    )

    print(f"Transaction hash: {response.txhash}")


if __name__ == "__main__":
    example_usage()
