/**
 * Kotlin Custom Signer Example
 *
 * This example demonstrates how to implement a custom cryptographic signer in Kotlin
 * that uses BouncyCastle or other JVM cryptography libraries instead of the built-in
 * Rust implementation.
 *
 * This allows you to:
 * - Use Kotlin/Java's native cryptographic libraries
 * - Integrate with Android Keystore for hardware-backed keys
 * - Use biometric authentication on Android
 * - Implement custom key management strategies
 */

package com.burnt.mob.examples

import org.bouncycastle.crypto.params.ECPrivateKeyParameters
import org.bouncycastle.crypto.params.ECPublicKeyParameters
import org.bouncycastle.crypto.signers.ECDSASigner
import org.bouncycastle.jce.ECNamedCurveTable
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.bouncycastle.jce.spec.ECNamedCurveParameterSpec
import org.bouncycastle.math.ec.ECPoint
import java.math.BigInteger
import java.security.MessageDigest
import java.security.Security

// Import the mob library (generated by UniFFI)
import mob.*

/**
 * Custom cryptographic signer implemented in Kotlin using BouncyCastle.
 *
 * This class implements the CryptoSigner interface defined in Rust, allowing
 * the mob library to use Kotlin's cryptographic implementations.
 */
class KotlinCryptoSigner(
    privateKeyBytes: ByteArray,
    private val addressPrefix: String
) : CryptoSigner {

    private val privateKey: BigInteger
    private val publicKeyBytes: ByteArray
    private val addressValue: String

    init {
        // Add BouncyCastle as security provider
        Security.addProvider(BouncyCastleProvider())

        // Load the secp256k1 curve parameters
        val ecParams = ECNamedCurveTable.getParameterSpec("secp256k1")

        // Create private key from bytes
        privateKey = BigInteger(1, privateKeyBytes)

        // Generate public key point
        val publicKeyPoint: ECPoint = ecParams.g.multiply(privateKey)

        // Get compressed public key (33 bytes)
        publicKeyBytes = publicKeyPoint.getEncoded(true)

        // Generate address from public key
        addressValue = generateAddress(publicKeyBytes, addressPrefix)
    }

    /**
     * Initialize from Android Keystore (Android only).
     *
     * This allows keys to be stored in hardware-backed secure storage
     * and never leave the device.
     */
    companion object {
        @JvmStatic
        fun fromAndroidKeystore(
            keyAlias: String,
            addressPrefix: String
        ): KotlinCryptoSigner {
            // In production Android app, load from Android Keystore
            // This is a simplified example
            val keyStore = java.security.KeyStore.getInstance("AndroidKeyStore")
            keyStore.load(null)

            val entry = keyStore.getEntry(keyAlias, null) as java.security.KeyStore.PrivateKeyEntry
            val privateKey = entry.privateKey

            // Extract private key bytes (implementation depends on key type)
            val privateKeyBytes = privateKey.encoded

            return KotlinCryptoSigner(privateKeyBytes, addressPrefix)
        }

        /**
         * Generate a bech32 address from a public key.
         */
        private fun generateAddress(publicKey: ByteArray, prefix: String): String {
            // SHA256 hash of the public key
            val sha256 = MessageDigest.getInstance("SHA-256")
            val sha256Hash = sha256.digest(publicKey)

            // RIPEMD160 hash of the SHA256 hash
            val ripemd160 = MessageDigest.getInstance("RIPEMD160", "BC")
            val addressHash = ripemd160.digest(sha256Hash)

            // Convert to bech32 format
            return Bech32.encode(prefix, addressHash)
        }

        /**
         * Normalize signature to low-S form (required by Cosmos SDK).
         */
        private fun normalizeLowS(s: BigInteger, curveOrder: BigInteger): BigInteger {
            val halfOrder = curveOrder.shiftRight(1)
            return if (s > halfOrder) {
                curveOrder.subtract(s)
            } else {
                s
            }
        }
    }

    // MARK: - CryptoSigner Interface Implementation

    override fun address(): String {
        return addressValue
    }

    override fun publicKey(): ByteArray {
        return publicKeyBytes
    }

    override fun addressPrefix(): String {
        return addressPrefix
    }

    override fun signBytes(message: ByteArray): ByteArray {
        try {
            // Hash the message with SHA256 (as required by Cosmos)
            val sha256 = MessageDigest.getInstance("SHA-256")
            val messageHash = sha256.digest(message)

            // Get secp256k1 curve parameters
            val ecParams = ECNamedCurveTable.getParameterSpec("secp256k1")

            // Create ECDSA signer
            val signer = ECDSASigner()
            val privKeyParams = ECPrivateKeyParameters(privateKey, ecParams)
            signer.init(true, privKeyParams)

            // Sign the hash
            val signature = signer.generateSignature(messageHash)
            var r = signature[0]
            var s = signature[1]

            // Normalize to low-S form (required by Cosmos SDK)
            s = normalizeLowS(s, ecParams.n)

            // Convert r and s to 32-byte big-endian format
            val rBytes = r.toByteArray().let {
                when {
                    it.size < 32 -> ByteArray(32 - it.size) + it
                    it.size > 32 -> it.copyOfRange(it.size - 32, it.size)
                    else -> it
                }
            }

            val sBytes = s.toByteArray().let {
                when {
                    it.size < 32 -> ByteArray(32 - it.size) + it
                    it.size > 32 -> it.copyOfRange(it.size - 32, it.size)
                    else -> it
                }
            }

            // Return r || s as 64 bytes
            return rBytes + sBytes

        } catch (e: Exception) {
            throw SignerError.SigningFailed("Failed to sign message: ${e.message}")
        }
    }
}

/**
 * Simple Bech32 encoding implementation.
 * In production, use a proper bech32 library.
 */
object Bech32 {
    private const val CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"

    fun encode(hrp: String, data: ByteArray): String {
        // Convert 8-bit bytes to 5-bit groups
        val fiveBitData = convertBits(data, 8, 5, true)

        // Calculate checksum
        val checksum = createChecksum(hrp, fiveBitData)

        // Combine data and checksum
        val combined = fiveBitData + checksum

        // Encode to bech32 string
        val encoded = combined.map { CHARSET[it.toInt()] }.joinToString("")

        return "$hrp${'1'}$encoded"
    }

    private fun convertBits(
        data: ByteArray,
        fromBits: Int,
        toBits: Int,
        pad: Boolean
    ): ByteArray {
        var acc = 0
        var bits = 0
        val result = mutableListOf<Byte>()
        val maxv = (1 shl toBits) - 1

        for (value in data) {
            acc = (acc shl fromBits) or (value.toInt() and 0xff)
            bits += fromBits
            while (bits >= toBits) {
                bits -= toBits
                result.add(((acc shr bits) and maxv).toByte())
            }
        }

        if (pad && bits > 0) {
            result.add(((acc shl (toBits - bits)) and maxv).toByte())
        }

        return result.toByteArray()
    }

    private fun createChecksum(hrp: String, data: ByteArray): ByteArray {
        // Simplified checksum - use proper bech32 checksum in production
        return ByteArray(6) { 0 }
    }
}

// MARK: - Example Usage

fun exampleUsage() {
    // Generate or load a private key (32 bytes)
    // In production, load this securely from Android Keystore, etc.
    val privateKeyHex = "your_private_key_hex_here"
    val privateKeyBytes = privateKeyHex.chunked(2)
        .map { it.toInt(16).toByte() }
        .toByteArray()

    // Create the Kotlin-based signer
    val signer = KotlinCryptoSigner(privateKeyBytes, "xion")

    println("Address: ${signer.address()}")
    println("Public Key: ${signer.publicKey().joinToString("") { "%02x".format(it) }}")

    // Create a mob client
    val config = ChainConfig(
        chainId = "xion-testnet-1",
        rpcEndpoint = "https://rpc.xion-testnet-1.burnt.com:443",
        addressPrefix = "xion"
    )

    val client = Client.newWithSigner(config, signer)

    // Now you can use the client with your custom Kotlin signer!
    // The client will call your Kotlin implementation for all signing operations

    // Send tokens using the Kotlin signer
    val response = client.send(
        toAddress = "xion1recipient...",
        amount = listOf(Coin("uxion", "1000000")),
        memo = "Transfer using Kotlin signer"
    )

    println("Transaction hash: ${response.txhash}")
}

fun main() {
    exampleUsage()
}
